######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 21 16:44:39 2022
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h tlist.h \
    tarchive.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp tlist.cpp \
    tarchive.cpp

DISTFILES += \
    archive \
    current

RESOURCES += \
    icons.qrc
